spring.application.name=todoapp

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/todo
spring.datasource.username=todo
spring.datasource.password=todo

jwt.secret=your-very-long-secret-key-that-is-at-least-32-bytes-long
jwt.expiration=3600000
